name: Releases

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean compile war:war --file pom.xml
    - name: Rename file
      run: mv ${GITHUB_WORKSPACE}/target/*.war ./rechnungless.war
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./rechnungless.war"
    - name: Downcase repository_owner
      run: |
        echo "REPOOWNER=${GITHUB_REPOSITORY_OWNER@L}" >> "${GITHUB_ENV}"
    - name: Strip Patch from Version
      run: |
        echo "MAJMINVERSION=$(echo "${{github.ref_name}}" | egrep -o "v[0-9]+\.[0-9]+")" >> "${GITHUB_ENV}"
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: 'Build and push Image'
      run: |
        docker build . --tag ghcr.io/${REPOOWNER}/rechnunglessconverter:${{github.ref_name}} --tag ghcr.io/${REPOOWNER}/rechnunglessconverter:${MAJMINVERSION} --tag ghcr.io/${REPOOWNER}/rechnunglessconverter:latest
        docker push ghcr.io/${REPOOWNER}/rechnunglessconverter --all-tags